### ISSUE TITLE
VolzSIRTest error for BEAST 2.5

### ISSUE THREAD

**Issue by walterxie** [BEAST2-Dev/phylodynamics#3]
beast.util.TreeParser$TreeParsingException: mismatched input ';' expecting {COMMA, ')'}
	at beast.util.TreeParser$1.syntaxError(TreeParser.java:362)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:299)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at beast.util.treeparser.NewickParser.node(NewickParser.java:225)
	at beast.util.treeparser.NewickParser.tree(NewickParser.java:123)
	at beast.util.TreeParser.parseNewick(TreeParser.java:380)
	at beast.util.TreeParser.initAndValidate(TreeParser.java:157)
	at beast.core.BEASTInterface.initByName(BEASTInterface.java:103)
	at test.beast.BEASTTestCase.getTree(BEASTTestCase.java:30)
	at test.phylodynamics.epidemiology.VolzSIRTest.testVolzSIR(VolzSIRTest.java:30)
	...

**Comment by walterxie** [comment]
It was a bug in the given tree. But after I corrected it, there was an error to create `Coalescent` given `DeterministicCoalescentSIR` because the latter was not inherited from `PopulationFunction`. It looks `VolzSIRTest` is still in development.
