### ISSUE TITLE
StochasticCoalescentTest cannot be found running build.xml

### ISSUE THREAD

**Issue by walterxie** [BEAST2-Dev/phylodynamics#5]
Run "build_all_phylodynamics" in build.xml:

<error message="test.phylodynamics.epidemiology.StochasticCoalescentTest" type="java.lang.ClassNotFoundException">java.lang.ClassNotFoundException: test.phylodynamics.epidemiology.StochasticCoalescentTest
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
</error>

**Comment by walterxie** [comment]
@denisekuehnert 
I fixed it, and removed the class path of MASTER and BEASTLab, which I do not think they are still used by phylodynamics.
